version: "3"
services:
  api:
    container_name: hearlers-nest-api-dev
    restart: always
    image: node:20.11.0
    working_dir: /usr/src/app
    command: bash -c "yarn install && yarn start:dev"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "50051:50051"
