export enum ActivityType {
  // 세션 관련
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  SESSION_START = "SESSION_START",
  SESSION_END = "SESSION_END",

  // 상담 관련
  CONSULTATION_START = "CONSULTATION_START",
  CONSULTATION_END = "CONSULTATION_END",

  // 프로필 관련
  PROFILE_UPDATE = "PROFILE_UPDATE",
  PROFILE_VIEW = "PROFILE_VIEW",

  // 감정 관련
  MOOD_CHECK = "MOOD_CHECK",
  EMOTION_RECORD = "EMOTION_RECORD",

  // 콘텐츠 관련
  CONTENT_VIEW = "CONTENT_VIEW",
  CONTENT_SAVE = "CONTENT_SAVE",
  CONTENT_SHARE = "CONTENT_SHARE",

  // 피드백 관련
  FEEDBACK_SUBMIT = "FEEDBACK_SUBMIT",
  RATING_SUBMIT = "RATING_SUBMIT",

  // 결제 관련
  SUBSCRIPTION_START = "SUBSCRIPTION_START",
  SUBSCRIPTION_CANCEL = "SUBSCRIPTION_CANCEL",
  PAYMENT_COMPLETE = "PAYMENT_COMPLETE",

  // 메시지 관련
  MESSAGE_SENT = "MESSAGE_SENT",
}
