export enum PromptCategory {
  INITIAL_ASSESSMENT = "INITIAL_ASSESSMENT", // 초기 평가
  EMOTIONAL_SUPPORT = "EMOTIONAL_SUPPORT", // 감정적 지원
  STRESS_MANAGEMENT = "STRESS_MANAGEMENT", // 스트레스 관리
  RELATIONSHIP = "RELATIONSHIP", // 대인 관계
  ANXIETY = "ANXIETY", // 불안
  DEPRESSION = "DEPRESSION", // 우울
  SELF_ESTEEM = "SELF_ESTEEM", // 자존감
  TRAUMA = "TRAUMA", // 트라우마
  CAREER = "CAREER", // 진로/경력
  DAILY_REFLECTION = "DAILY_REFLECTION", // 일상 성찰
}
