name: Deploy to dev

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.DEV_EC2_HOST }} << EOF
            cd ~/handybus-api
            git pull origin main
            sudo docker-compose -f docker-compose.dev.yml pull
            sudo docker-compose -f docker-compose.dev.yml up -d --build
          EOF
